### ISSUE TITLE
Managing Calendar component state

### ISSUE THREAD

**Issue by readeral** [Vision100IT/ui#14]
Issue 1:
Queries are defined per source, for example, the drupal API we’ve set up requires the following URL query string:

```
display_id=services_1&date_range_start[value][date]=2018/11/01&date_range_end[value][date]=2018/11/30
```

but the Elvanto API requires the following parameter object:

```json
{
 	"page": 1,
	"page_size": 100,
 	"start": "2019-12-01",
	"end": "2019-12-31",
	"fields": [
		"locations",
		"etc…"
	]
}
```

This means query format, as well as the date range, needs to be passed to the useFetch() hook, or the useFetch hook needs to know which API we’re querying and transform to the required format before fetching the data. This can be done within a custom hook called useDrupal and useElvanto respectively

NO PROBLEM

Issue 2:
The response from the API endpoints need to be normalised according to what the Calendar component requires. In the case of Elvanto, it’s +10 hours onto events, for Drupal it’s re-naming event.nid to calendar_id

This means that both the useFetch() and normalising data should be encased in one function which handles both the preparation of the parameters and the cleaning up of the returned data. That’s ok, we can do that within the useDrupal and useElvanto

NO PROBLEM

Issue 3:
The display state (the applicable date ranges) is handled by the Calendar component, and so the state that needs passing to the component which handles the API call, needs to originate from within Calendar. This means that either useDrupal/useElvanto are programmed into Calendar (which means the component is no longer agnostic), OR a wrapper around Calendar calls useElvanto/useDrupal. If that’s the case, either the display state is passed up from Calendar to the wrapper component (two-way data flow), OR the display state is managed by the wrapper component (making Calendar a pure function)

**Comment by BarryThePenguin** [comment]
I imagine we'd end up with something like the following...

```js
// use-calendar-reducer.js

export default function useCalendarReducer() {
	const [state, dispatch] = useReducer(...);

	return ...;
}
```

```js
// use-drupal-events.js

import useCalendarReducer from './use-calendar-reducer.js';

export default useDrupalEvents(apiUrl, ...) {
	const [state, dispatch] = useCalendarReducer();
	const [events, loading, error] = useFetch(apiUrl, ...);
	const normalizedDrupalEvents = normalize(events);

	return [normalizedDrupalEvents, loading, error, dispatch];
}

```

```js
// use-elvanto-events.js

import useCalendarReducer from './use-calendar-reducer.js';

export default useElvantoEvents(apiUrl, ...) {
	const [state, dispatch] = useCalendarReducer();
	const [events, loading, error] = useFetch(apiUrl, ...);
	const normalizedElvantoEvents = normalize(events);

	return [normalizedElvantoEvents, loading, error, dispatch];
}
```

```js
// drupal-calendar.js

export function DrupalCalendar({ apiUrl }) {
	const [events, loading, error, dispatch] = useDrupalEvents(apiUrl, ...);

	return <Calendar events={events} dispatch={dispatch} {...} />
}
```

```js
// elvanto-calendar.js

export function ElvantoCalendar({ apiUrl }) {
	const [events, loading, error, dispatch] = useElvantoEvents(apiUrl, ...);

	return <Calendar events={events} dispatch={dispatch} {...} />
}
```

**Comment by readeral** [comment]
This was fixed your rewrite. Closing :)
